const data = [
    { page: 1 },
    { name: "두 수의 곱 구하기", link: 120804, ans: "( num1, num2 ) => num1 * num2;" },
    { name: "두 수의 나눗셈", link: 120806, ans: "( num1, num2 ) => ~~( num1 * 1000 / num2 );" },
    { name: "숫자 비교하기", link: 120807, ans: "( num1, num2 ) => num1 - num2 ? -1 : 1;" },
    { name: "나머지 구하기", link: 120810, ans: "( num1, num2 ) => num1 % num2;" },
    { name: "나이 출력", link: 120820, ans: "age => 2023 - age;" },
    { name: "두 수의 차 구하기", link: 120803, ans: "( num1, num2 ) => num1 - num2; " },
    { name: "몫 구하기", link: 120805, ans: "( num1, num2 ) => Math.floor( num1 / num2 );" },
    { name: "머쓱이보다 키 큰 사람", link: 120585, ans: "( arr, height ) => arr.filter( a => a > height ).length;" },
    { name: "두 수의 합 구하기", link: 120802, ans: "( num1, num2 ) => num1 + num2;" },
    { name: "피자 나눠 먹기 (1)", link: 120814, ans: "n => Math.ceil( n / 7 );" },
    { name: "피자 나눠 먹기 (3)", link: 120816, ans: "( slice, n ) => Math.ceil( n / slice );" },
    { name: "배열의 평균값", link: 120817, ans: "numbers => numbers.reduce( ( a, b ) => a + b, 0 ) / numbers.length;" },
    { name: "아이스 아메리카노", link: 120819, ans: "m => [ ~~( m / 5500 ), m % 5500 ];" },
    { name: "배열 뒤집기", link: 120821, ans: "num_list => num_list.reverse();" },
    { name: "뒤집힌 문자열", link: 120822, ans: "my_string => my_string.split(\"\").reverse().join(\"\");" },
    { name: "짝수 홀수 개수", link: 120824, ans: "l => l.reduce( ( r, n ) => n % 2 ? [ r[0], r[1] + 1 ] : [ r[0] + 1, r[1] ], [ 0, 0 ] );" },
    { name: "문자 반복 출력하기", link: 120825, ans: "( str, n ) => str.split(\"\").map( char => char.repeat(n) ).join(\"\");" },
    { name: "특정 문자 제거하기", link: 120826, ans: "( str, char ) => str.replaceAll( char, \"\" );" },
    { name: "각도기", link: 120829, ans: "a => a < 90 ? 1 : a === 90 ? 2 : a < 180 ? 3 : 4;" },
    { name: "양꼬치", link: 120830, ans: "( n, k ) => n * 12000 + ( k - Math.floor( n / 10 ) ) * 2000;" },
    { page: 2 },
    { name: "짝수의 합", link: 120831, ans: "n => ( Math.floor( n / 2 ) + 0.5 ) ** 2 - 0.25;" },
    { name: "배열 자르기", link: 120833, ans: "( numbers, num1, num2 ) => numbers.slice( num1, num2 + 1 );" },
    { name: "순서쌍의 개수", link: 120836, ans: "n => '@'.repeat(n).split(\"\").filter( ( _, i ) => !( n % i ) ).length;" },
    { name: "점의 위치 구하기", link: 120841, ans: "dot => 1 + ( dot[0] * dot[1] < 0 ) + ( dot[1] < 0 ) * 2;" },
    { name: "최댓값 만들기(1)", link: 120847, ans: "numbers => numbers.sort( ( a, b ) => b - a ).slice( 0, 2 ).reduce( ( r, num ) => r * num, 1 );" },
    { name: "모음 제거", link: 120849, ans: "str => \"aeiou\".split(\"\").reduce( ( r, char ) => r.replaceAll( char, \"\" ), str );" },
    { name: "숨어있는 숫자의 덧셈 (1)", link: 120851, ans: "str => str.split(\"\").filter( c => !isNaN(c) ).reduce( ( r, num ) => r + Number(num), 0 );" },
    { name: "배열 원소의 길이", link: 120854, ans: "strlist => strlist.map( a => a.length );" },
    { name: "삼각형의 완성조건 (1)", link: 120889, ans: "sides => sides.sort( ( a, b ) => b - a ).reduce( ( r, num, i ) => i ? r - num : num, 2763 ) < 0 ? 1 : 2;" },
    { name: "대문자와 소문자", link: 120893, ans: "str => str.split(\"\").map( char => char.charCodeAt() > 96 ? char.toUpperCase() : char.toLowerCase() ).join(\"\");" },
    { name: "편지", link: 120898, ans: "message => message.length * 2;" },
    { name: "가장 큰 수 찾기", link: 120899, ans: "arr => arr.reduce( ( r, n, i ) => n > r[0] ? [ n, i ] : r, [ -1, 2763 ] );" },
    { name: "배열의 유사도", link: 120903, ans: "( s1, s2 ) => s1.length + s2.length - [...new Set([ ...s1, ...s2 ])].length;" },
    { name: "n의 배수 고르기", link: 120905, ans: "( n, numlist ) => numlist.filter( num => !( num % n ) ); " },
    { name: "자릿수 더하기", link: 120906, ans: "n => `${n}`.split(\"\").reduce( ( r, a ) => +a + r, 0 );" },
    { name: "문자열안에 문자열", link: 120908, ans: "( str1, str2 ) => str1.split(str2).length - 1 ? 1 : 2;" },
    { name: "제곱수 판별하기", link: 120909, ans: "n => Math.sqrt(n) % 1 ? 2 : 1;" },
    { name: "세균 증식", link: 120910, ans: "( n, t ) => n * 2 ** t;" },
    { name: "약수 구하기", link: 120897, ans: "n => '@'.repeat(n).split(\"\").map( ( _, i ) => i + 1 ).filter( i => !( n % i ) );" },
    { name: "짝수는 싫어요", link: 120813, ans: "n => Array(Math.ceil( n / 2 )).fill(2763).map( ( _, i ) => i * 2 + 1 );" },
    { page: 3 },
    { name: "문자열을 정수로 변환하기", link: 181848, ans: "n_str => Number(n_str);" },
    { name: "문자열 정수의 합", link: 181849, ans: "num_str => num_str.split(\"\").reduce( ( a, b ) => a + Number(b), 0 );" },
    { page: 4 },
    { name: "뒤에서 5등 위로", link: 181852, ans: "list => list.sort( ( a, b ) => a - b ).slice(5);" },
    { name: "뒤에서 5등까지", link: 181853, ans: "num_list => num_list.sort( ( a, b ) => a - b ).filter( ( num, i ) => i < 5 );" },
    { name: "배열의 길이에 따라 다른 연산하기", link: 181854, ans: "( arr, n ) => arr.map( ( num, i ) => ( arr.length % 2 === i % 2 ) ? num : num + n );" },
    { name: "배열 비교하기", link: 181856, ans: "( arr1, arr2 ) => ( sigmaFunction => arr1.length !== arr2.length ? ( arr1.length > arr2.length ) * 2 - 1 : ( ( sigma1, sigma2 ) => sigma1 !== sigma2 ? ( sigma1 > sigma2 ) * 2 - 1 : 0 )( sigmaFunction(arr1), sigmaFunction(arr2) ) )( arr => arr.reduce( ( nusan, number ) => nusan + number, 0 ) );" },
    { name: "배열의 원소만큼 추가하기", link: 181861, ans: "arr => arr.reduce( ( r, num ) => [ ...r, ...new Array(num).fill(num) ], [] );" },
    { name: "rny_string", link: 181863, ans: "rny_string => rny_string.replaceAll( 'm', \"rn\" );" },
    { name: "문자열 바꿔서 찾기", link: 181864, ans: "( myString, pat ) => myString.indexOf(pat.split(\"\").map( char => char === 'A' ? 'B' : 'A' ).join(\"\")) === -1 ? 0 : 1;" },
    { name: "x 사이의 개수", link: 181867, ans: "myString => myString.split('x').map( arr => arr.length );" },
    { page: 11 },
    { name: "특이한 정렬", link: 120880, ans: "( numlist, n ) => ( BFDIA => numlist.sort(BFDIA) )( ( a, b ) => Math.abs( n - a ) - Math.abs( n - b ) - ( a > b ) * 0.5 );" },
    { name: "안전지대", link: 120866, ans: "b => b.length ** 2 - b.map( ( bb, i ) => bb.map( ( s, ii ) => new Array(9).fill(2).reduce( ( r, _ ,ri ) => r || b[Math.max( Math.min( ~~(ri/3)-1+i, b.length-1 ), 0 )][Math.max( Math.min( ri%3-1+ii, b.length-1 ), 0 )], 0 ) ).filter(Boolean).length ).reduce( ( rFinal, nFinal ) => rFinal + nFinal, 0 );" },
    { name: "주사위 게임 3", link: 181916, ans: "( a, b, c, d ) => ( plate => plate[0].sideNum === 4 ? plate[0].sideName * 1111 : plate[0].sideNum === 3 ? ( plate[0].sideName * 10 + plate[1].sideName ) ** 2 : plate[1].sideNum === 2 ? plate[1].sideName ** 2 - plate[0].sideName ** 2 :  plate[0].sideNum === 2 ? plate[1].sideName * plate[2].sideName : plate[0].sideName )('@'.repeat(6).split(\"\").map( ( trash, i ) => ({ sideName: i + 1, sideNum: 4 - `${a}${b}${c}${d}`.split( i + 1 ).join(\"\").length }) ).sort( ( x, y ) => y.sideNum - x.sideNum ));" },
    { page: 12 },
    { name: "겹치는 선분의 길이", link: 120876, ans: "lines => [ lines.map( line => '@'.repeat( line[1] - line[0] ).split(\"\").map( ( empty, i ) => i + line[0] )), '@' ].reduce( ( a, data, i ) => !i ? { lines: data, answer: '@'.repeat(201).split(\"\").map( ( empty, i ) => i - 100 ).filter( i => data.reduce( ( b, dots ) => dots.includes(i) ? b + 1 : b, 0 ) > 1 ) } : a.answer.length, {} );" },
    { name: "옹알이 (1)", link: 120956, ans: "babbling => babbling.reduce( ( a, word ) => a.cans.reduce( ( b, can ) => b.split(can).join('@'), word ).split('@').join(\"\") ? a : { cans: a.cans, answer: a.answer + 1 }, { cans: [ \"aya\", \"ye\", \"woo\", \"ma\" ], answer: 0 } ).answer;" }
];
data.forEach( ( aData, index ) => document.querySelector("dl").innerHTML += aData.page ? `<h3 class="page${aData.page}">page ${aData.page}</h3>` : `<dt><a href="https://school.programmers.co.kr/learn/courses/30/lessons/${aData.link}">${aData.name}</a></dt><dd>const solution = ${aData.ans}</dd>` );